apiVersion: v1
kind: Namespace
metadata:
  name: myapp
  labels:
    app: employees
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
  labels:
   app: employees
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30000
  selector:
    app: employees
