apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: employees
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: myapp
        image: 218146516368.dkr.ecr.us-east-1.amazonaws.com/app_ecr:v0.1
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.244.0.11"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
