apiVersion: v1
kind: Namespace
metadata:
  name: mysqldb
  labels:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysqldb
  labels:
    app: mysql
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: 218146516368.dkr.ecr.us-east-1.amazonaws.com/mysql_ecr:v1.0
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
