apiVersion: v1
kind: Namespace
metadata:
  name: mysql
  labels:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    app: mysql
    owner: glaiza
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
