apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
    owner: glaiza
  name: mysql-pod
spec:
  containers:
  - image: 218146516368.dkr.ecr.us-east-1.amazonaws.com/mysql_ecr:v1.0
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
